# Generated by Django 5.0.14 on 2026-06-06 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_consume_credits',
            field=models.BooleanField(default=True, verbose_name='Peut consommer des crédits'),
        ),
        migrations.AlterField(
            model_name='cabinet',
            name='schema_name',
            field=models.CharField(default='public', max_length=63, unique=True),
        ),
        migrations.AlterField(
            model_name='domain',
            name='domain',
            field=models.CharField(max_length=253, unique=True),
        ),
        migrations.AlterField(
            model_name='domain',
            name='is_primary',
            field=models.BooleanField(default=True),
        ),
    ]
