# Generated by Django 5.0.14 on 2026-06-07 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_can_consume_credits_alter_cabinet_schema_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', 'Connexion'), ('logout', 'Déconnexion'), ('report_created', 'Rapport créé'), ('report_downloaded', 'Rapport téléchargé'), ('credits_purchased', 'Crédits achetés'), ('credits_allocated', 'Crédits alloués'), ('user_created', 'Utilisateur créé'), ('user_deleted', 'Utilisateur supprimé'), ('impersonate', "Usurpation d'identité")], max_length=50),
        ),
    ]
