# Generated by Django 5.0.14 on 2026-06-08 18:46

import django_tenants.postgresql_backend.base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_auditlog_cabinet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cabinet",
            name="schema_name",
            field=models.CharField(
                db_index=True,
                max_length=63,
                unique=True,
                validators=[django_tenants.postgresql_backend.base._check_schema_name],
            ),
        ),
        migrations.AlterField(
            model_name="domain",
            name="domain",
            field=models.CharField(db_index=True, max_length=253, unique=True),
        ),
        migrations.AlterField(
            model_name="domain",
            name="is_primary",
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
