# Generated by Django 5.0.14 on 2026-06-09 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_cabinet_schema_name_alter_domain_domain_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabinet',
            name='schema_name',
            field=models.CharField(default='public', max_length=63, unique=True),
        ),
        migrations.AlterField(
            model_name='domain',
            name='domain',
            field=models.CharField(max_length=253, unique=True),
        ),
        migrations.AlterField(
            model_name='domain',
            name='is_primary',
            field=models.BooleanField(default=True),
        ),
    ]
