# Generated by Django 5.0.14 on 2026-01-21 19:21

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CarbonEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fec_line_number", models.IntegerField(verbose_name="N° ligne FEC")),
                ("compte_num", models.CharField(max_length=20, verbose_name="Compte")),
                ("compte_lib", models.CharField(blank=True, max_length=255)),
                ("ecriture_lib", models.CharField(blank=True, max_length=500)),
                (
                    "debit",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=15
                    ),
                ),
                (
                    "credit",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=15
                    ),
                ),
                (
                    "co2_kg",
                    models.DecimalField(
                        decimal_places=4, max_digits=15, verbose_name="kg CO2e"
                    ),
                ),
                (
                    "dqr",
                    models.IntegerField(
                        choices=[
                            (1, "1 - Très faible (fallback)"),
                            (2, "2 - Faible (estimation)"),
                            (3, "3 - Moyen (PCG standard)"),
                            (4, "4 - Bon (NLP enrichi)"),
                            (5, "5 - Excellent (donnée primaire)"),
                        ],
                        default=3,
                        verbose_name="Score qualité",
                    ),
                ),
                (
                    "mapping_method",
                    models.CharField(
                        choices=[
                            ("pcg_exact", "PCG exact"),
                            ("pcg_prefix", "PCG préfixe"),
                            ("nlp", "NLP libellé"),
                            ("manual", "Manuel"),
                            ("fallback", "Fallback"),
                        ],
                        default="pcg_prefix",
                        max_length=20,
                    ),
                ),
                (
                    "scope",
                    models.IntegerField(
                        choices=[
                            (1, "Scope 1 - Direct"),
                            (2, "Scope 2 - Indirect énergie"),
                            (3, "Scope 3 - Autres indirects"),
                        ],
                        default=3,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Entrée carbone",
                "verbose_name_plural": "Entrées carbone",
                "ordering": ["fec_line_number"],
            },
        ),
        migrations.CreateModel(
            name="EmissionFactor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ademe_id", models.CharField(max_length=100, verbose_name="ID ADEME")),
                ("name", models.CharField(max_length=500, verbose_name="Nom")),
                (
                    "category",
                    models.CharField(max_length=255, verbose_name="Catégorie"),
                ),
                ("subcategory", models.CharField(blank=True, max_length=255)),
                (
                    "value_kg_co2_per_euro",
                    models.DecimalField(
                        decimal_places=6, max_digits=12, verbose_name="kg CO2e / €"
                    ),
                ),
                (
                    "value_kg_co2_per_unit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=12,
                        null=True,
                        verbose_name="kg CO2e / unité",
                    ),
                ),
                (
                    "unit",
                    models.CharField(default="€", max_length=50, verbose_name="Unité"),
                ),
                (
                    "uncertainty_percent",
                    models.IntegerField(default=50, verbose_name="Incertitude (%)"),
                ),
                (
                    "version",
                    models.CharField(max_length=20, verbose_name="Version ADEME"),
                ),
                ("valid_from", models.DateField(verbose_name="Valide depuis")),
                ("valid_until", models.DateField(blank=True, null=True)),
                (
                    "scope",
                    models.IntegerField(
                        choices=[
                            (1, "Scope 1 - Direct"),
                            (2, "Scope 2 - Indirect énergie"),
                            (3, "Scope 3 - Autres indirects"),
                        ],
                        default=3,
                    ),
                ),
                ("source_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Facteur d'émission",
                "verbose_name_plural": "Facteurs d'émission",
            },
        ),
        migrations.CreateModel(
            name="PCGMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pcg_prefix",
                    models.CharField(max_length=10, verbose_name="Préfixe compte PCG"),
                ),
                ("pcg_description", models.CharField(blank=True, max_length=255)),
                (
                    "priority",
                    models.IntegerField(
                        default=0,
                        help_text="Plus élevé = plus prioritaire (exact match > racine)",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Mapping PCG",
                "verbose_name_plural": "Mappings PCG",
                "ordering": ["-priority", "pcg_prefix"],
            },
        ),
    ]
