# Generated by Django 5.0.14 on 2026-01-21 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("carbon_engine", "0001_initial"),
        ("report_generator", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="carbonentry",
            name="report",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="carbon_entries",
                to="report_generator.report",
            ),
        ),
        migrations.AddIndex(
            model_name="emissionfactor",
            index=models.Index(
                fields=["category"], name="carbon_engi_categor_a1c6bc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emissionfactor",
            index=models.Index(fields=["scope"], name="carbon_engi_scope_dbc937_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="emissionfactor",
            unique_together={("ademe_id", "version")},
        ),
        migrations.AddField(
            model_name="carbonentry",
            name="emission_factor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="carbon_entries",
                to="carbon_engine.emissionfactor",
            ),
        ),
        migrations.AddField(
            model_name="pcgmapping",
            name="emission_factor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pcg_mappings",
                to="carbon_engine.emissionfactor",
            ),
        ),
        migrations.AddIndex(
            model_name="carbonentry",
            index=models.Index(
                fields=["report", "scope"], name="carbon_engi_report__d81f3d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="carbonentry",
            index=models.Index(
                fields=["compte_num"], name="carbon_engi_compte__454140_idx"
            ),
        ),
    ]
