# Generated by Django 5.0.14 on 2026-06-05 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbon_engine', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InseeDeflator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Année')),
                ('naf_code', models.CharField(blank=True, max_length=5, null=True, verbose_name='Code NAF (optionnel)')),
                ('index_value', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Indice de prix')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Déflateur Insee',
                'verbose_name_plural': 'Déflateurs Insee',
                'ordering': ['-year', 'naf_code'],
                'unique_together': {('year', 'naf_code')},
            },
        ),
    ]
