# Generated by Django 5.0.14 on 2026-01-22 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbon_engine', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbonentry',
            name='emission_factor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='carbon_entries', to='carbon_engine.emissionfactor'),
        ),
    ]
