# Generated by Django 5.0.14 on 2026-06-05 19:28

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbon_engine', '0003_inseedeflator'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbonentry',
            name='deflator_factor',
            field=models.DecimalField(decimal_places=4, default=Decimal('1.0'), max_digits=10, verbose_name='Facteur de déflation Insee'),
        ),
    ]
