# Generated by Django 5.0.14 on 2026-06-05 19:41

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbon_engine', '0004_carbonentry_deflator_factor'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inseedeflator',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='inseedeflator',
            name='index_value',
            field=models.DecimalField(decimal_places=4, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='Indice de prix'),
        ),
        migrations.AddConstraint(
            model_name='inseedeflator',
            constraint=models.UniqueConstraint(condition=models.Q(('naf_code__isnull', True)), fields=('year',), name='unique_year_global_deflator'),
        ),
        migrations.AddConstraint(
            model_name='inseedeflator',
            constraint=models.UniqueConstraint(condition=models.Q(('naf_code__isnull', False)), fields=('year', 'naf_code'), name='unique_year_naf_deflator'),
        ),
    ]
