# Generated by Django 5.0.14 on 2026-06-05 20:02

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ('carbon_engine', '0005_alter_inseedeflator_unique_together_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            "CREATE EXTENSION IF NOT EXISTS pg_trgm SCHEMA public;",
            "DROP EXTENSION IF EXISTS pg_trgm;"
        ),
    ]
