# Generated by Django 5.0.14 on 2026-06-05 20:03

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbon_engine', '0006_setup_pg_trgm'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbonentry',
            name='fournisseur_naf',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Code NAF fournisseur'),
        ),
        migrations.AlterField(
            model_name='carbonentry',
            name='mapping_method',
            field=models.CharField(choices=[('pcg_exact', 'PCG exact'), ('pcg_prefix', 'PCG préfixe'), ('naf', 'NAF Fournisseur'), ('nlp', 'NLP libellé'), ('manual', 'Manuel'), ('fallback', 'Fallback')], default='pcg_prefix', max_length=20),
        ),
        migrations.CreateModel(
            name='SireneStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siren', models.CharField(max_length=9, unique=True, verbose_name='SIREN')),
                ('denomination', models.CharField(max_length=255, verbose_name='Dénomination')),
                ('naf_code', models.CharField(max_length=5, verbose_name='Code NAF')),
            ],
            options={
                'verbose_name': 'Établissement Sirene',
                'verbose_name_plural': 'Établissements Sirene',
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['denomination'], name='sirene_denomination_gin', opclasses=['gin_trgm_ops'])],
            },
        ),
    ]
