# Generated by Django 5.0.14 on 2026-06-05 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carbon_engine", "0007_carbonentry_fournisseur_naf_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="carbonentry",
            name="physical_quantity",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=15,
                null=True,
                verbose_name="Quantité physique",
            ),
        ),
        migrations.AddField(
            model_name="carbonentry",
            name="physical_unit",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="carbonentry",
            name="dqr",
            field=models.IntegerField(
                choices=[
                    (1, "1 - Excellent (donnée primaire / physique)"),
                    (2, "2 - Bon (NLP enrichi)"),
                    (3, "3 - Moyen (NAF / PCG exact)"),
                    (4, "4 - Faible (PCG préfixe / monétaire)"),
                    (5, "5 - Très faible (fallback)"),
                ],
                default=3,
                verbose_name="Score qualité",
            ),
        ),
    ]
