# Generated by Django 5.0.14 on 2026-06-05 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbon_engine', '0008_carbonentry_physical_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbonentry',
            name='ecriture_date',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'écriture"),
        ),
    ]
