# Generated by Django 5.0.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbon_engine', '0009_carbonentry_ecriture_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbonentry',
            name='requires_physical_data',
            field=models.BooleanField(default=False, verbose_name='Saisie physique requise (hybridation)'),
        ),
        migrations.AlterField(
            model_name='carbonentry',
            name='dqr',
            field=models.IntegerField(choices=[(1, '1 - Excellent (donnée primaire / physique)'), (2, '2 - Bon (Fournisseur NAF)'), (3, '3 - Moyen (Désambiguïsation NLP)'), (4, '4 - Faible (PCG exact / préfixe monétaire)'), (5, '5 - Très faible (fallback)')], default=3, verbose_name='Score qualité'),
        ),
        migrations.AlterField(
            model_name='carbonentry',
            name='mapping_method',
            field=models.CharField(choices=[('hybrid_pending', 'En attente physique'), ('naf_supplier', 'Fournisseur (NAF)'), ('nlp_override', 'Désambiguïsation NLP'), ('pcg_exact', 'PCG exact'), ('pcg_prefix', 'PCG préfixe'), ('manual', 'Manuel'), ('fallback', 'Fallback'), ('exclusion', 'Exclu (Anti-double compte)')], default='pcg_prefix', max_length=20),
        ),
    ]
