# Generated by Django 5.0.14 on 2026-06-08 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carbon_engine", "0010_carbonentry_requires_physical_data_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CarbonFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "original_compte_num",
                    models.CharField(
                        max_length=20, verbose_name="Compte original (tronqué)"
                    ),
                ),
                (
                    "original_ecriture_lib",
                    models.CharField(
                        max_length=500, verbose_name="Libellé original (anonymisé)"
                    ),
                ),
                (
                    "corrected_category",
                    models.CharField(max_length=255, verbose_name="Catégorie corrigée"),
                ),
                (
                    "corrected_ademe_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="ID ADEME corrigé"
                    ),
                ),
                (
                    "used_for_training",
                    models.BooleanField(
                        default=False, verbose_name="Déjà utilisé pour l'entraînement"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Feedback de classification",
                "verbose_name_plural": "Feedbacks de classification",
            },
        ),
    ]
