# Generated by Django 5.0.14 on 2026-06-09 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbon_engine', '0011_carbonfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbonfeedback',
            name='corrected_dqr',
            field=models.IntegerField(default=3, verbose_name='Score DQR de la correction'),
        ),
    ]
