# Generated by Django 5.0.14 on 2026-06-09 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbon_engine', '0012_carbonfeedback_corrected_dqr'),
    ]

    operations = [
        migrations.AddField(
            model_name='emissionfactor',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Archivé (donnée historique)'),
        ),
    ]
