# Generated by Django 5.0.14 on 2026-06-09 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbon_engine', '0013_emissionfactor_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='sirenestock',
            name='naf_2025_etablissement',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='NAF 2025 Établissement'),
        ),
        migrations.AddField(
            model_name='sirenestock',
            name='naf_2025_unite_legale',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='NAF 2025 Unité Légale'),
        ),
    ]
