# Generated by Django 5.0.14 on 2026-06-05 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FECFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(
                        max_length=255, verbose_name="Nom fichier original"
                    ),
                ),
                (
                    "storage_path",
                    models.CharField(max_length=500, verbose_name="Chemin S3"),
                ),
                (
                    "file_size_bytes",
                    models.BigIntegerField(default=0, verbose_name="Taille (bytes)"),
                ),
                (
                    "row_count",
                    models.IntegerField(default=0, verbose_name="Nombre de lignes"),
                ),
                (
                    "encoding",
                    models.CharField(
                        default="utf-8", max_length=50, verbose_name="Encodage détecté"
                    ),
                ),
                (
                    "separator",
                    models.CharField(
                        default="\t", max_length=5, verbose_name="Séparateur"
                    ),
                ),
                (
                    "validation_status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("validating", "Validation en cours"),
                            ("valid", "Valide"),
                            ("invalid", "Invalide"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("validation_errors", models.JSONField(blank=True, default=list)),
                ("processing_started_at", models.DateTimeField(blank=True, null=True)),
                (
                    "processing_completed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("processing_time_ms", models.IntegerField(default=0)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Fichier FEC",
                "verbose_name_plural": "Fichiers FEC",
            },
        ),
        migrations.CreateModel(
            name="FECValidationRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("column_name", models.CharField(max_length=50, unique=True)),
                ("column_index", models.IntegerField()),
                ("is_required", models.BooleanField(default=True)),
                ("data_type", models.CharField(max_length=20)),
                ("max_length", models.IntegerField(blank=True, null=True)),
                ("regex_pattern", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Règle validation FEC",
                "verbose_name_plural": "Règles validation FEC",
                "ordering": ["column_index"],
            },
        ),
    ]
