# Generated by Django 5.0.14 on 2026-06-05 17:43

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "client_name",
                    models.CharField(max_length=255, verbose_name="Nom client"),
                ),
                ("client_siret", models.CharField(blank=True, max_length=14)),
                ("fiscal_year", models.IntegerField(verbose_name="Année fiscale")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("processing", "Traitement en cours"),
                            ("completed", "Terminé"),
                            ("failed", "Échec"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("progress_percent", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                (
                    "total_co2_kg",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=15,
                        verbose_name="Total CO2 (kg)",
                    ),
                ),
                (
                    "scope1_co2_kg",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=15
                    ),
                ),
                (
                    "scope2_co2_kg",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=15
                    ),
                ),
                (
                    "scope3_co2_kg",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=15
                    ),
                ),
                (
                    "average_dqr",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("3.00"),
                        max_digits=3,
                        verbose_name="Score qualité moyen",
                    ),
                ),
                ("pdf_url", models.URLField(blank=True, verbose_name="URL PDF")),
                ("pdf_generated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "emission_factors_version",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Version facteurs ADEME"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "cabinet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="core.cabinet",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Rapport",
                "verbose_name_plural": "Rapports",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReportAuditTrail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Créé"),
                            ("processing_started", "Traitement démarré"),
                            ("processing_completed", "Traitement terminé"),
                            ("processing_failed", "Traitement échoué"),
                            ("pdf_generated", "PDF généré"),
                            ("pdf_downloaded", "PDF téléchargé"),
                            ("entries_viewed", "Détails consultés"),
                            ("exported", "Exporté"),
                        ],
                        max_length=30,
                    ),
                ),
                ("details", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_trail",
                        to="report_generator.report",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit trail rapport",
                "verbose_name_plural": "Audit trails rapports",
                "ordering": ["-created_at"],
            },
        ),
    ]
