# Generated by Django 5.0.14 on 2026-06-06 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_generator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialityAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='materiality_assessment', to='report_generator.report')),
            ],
            options={
                'verbose_name': 'Évaluation Double Matérialité',
                'verbose_name_plural': 'Évaluations Double Matérialité',
            },
        ),
    ]
