# Generated by Django 5.0.14 on 2026-06-06 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_generator', '0002_materialityassessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='xbrl_validation_errors',
            field=models.JSONField(blank=True, null=True, verbose_name='Erreurs XBRL'),
        ),
        migrations.AddField(
            model_name='report',
            name='xbrl_validation_passed',
            field=models.BooleanField(default=False, verbose_name='Validation XBRL ESEF'),
        ),
    ]
