# Generated by Django 5.0.14 on 2026-06-06 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_generator', '0003_report_xbrl_validation_errors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='ixbrl_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='ixbrl_url',
            field=models.URLField(blank=True, verbose_name='URL iXBRL'),
        ),
        migrations.AlterField(
            model_name='reportaudittrail',
            name='action',
            field=models.CharField(choices=[('created', 'Créé'), ('processing_started', 'Traitement démarré'), ('processing_completed', 'Traitement terminé'), ('processing_failed', 'Traitement échoué'), ('pdf_generated', 'PDF généré'), ('pdf_downloaded', 'PDF téléchargé'), ('ixbrl_generated', 'iXBRL généré'), ('ixbrl_downloaded', 'iXBRL téléchargé'), ('entries_viewed', 'Détails consultés'), ('exported', 'Exporté')], max_length=30),
        ),
    ]
