# Generated by Django 5.0.14 on 2026-06-06 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_generator', '0004_report_ixbrl_generated_at_report_ixbrl_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='is_unlocked',
            field=models.BooleanField(default=False, verbose_name='Débloqué (Crédit consommé)'),
        ),
    ]
