# Generated by Django 5.0.14 on 2026-06-06 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_generator', '0005_report_is_unlocked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='xbrl_validation_passed',
            field=models.BooleanField(blank=True, null=True, verbose_name='Validation XBRL ESEF'),
        ),
    ]
