# Generated by Django 5.0.14 on 2026-06-08 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report_generator", "0006_alter_report_xbrl_validation_passed"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="total_energy_mwh",
            field=models.DecimalField(
                decimal_places=4,
                default=0,
                max_digits=15,
                verbose_name="Consommation énergétique (MWh) - ESRS E1-5",
            ),
        ),
    ]
